services:
  ubuntu:
    image: ${PULL_DOCKER_USERNAME}/ubuntu:${DOCKER_IMAGE_VERSION}
    build: .
    container_name: ubuntu_jammy
    command: /bin/bash -c "tail -f /dev/null"
    ports:
      - 80:80

