name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker compose build

    # - name: Tag the Docker image with commit's 7 letter 
    #   run: |
    #     TAG=${GITHUB_REF_NAME}-${GITHUB_SHA::7}
    #     echo "TAG=$TAG" >> $GITHUB_ENV
    
    - name: Tag the Docker image release date
      run: |
        RELEASE_DATE=$(date +"%d_%b_%Y")
        echo "RELEASE_DATE=$RELEASE_DATE" >> $GITHUB_ENV

    - name: Publish to Docker Hub with release date tag
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker tag ubuntu:1.0 ${{ secrets.DOCKER_HUB_USERNAME }}/ubuntu:$RELEASE_DATE
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ubuntu:$RELEASE_DATE
