name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: docker compose build

    - name: Get the release date
      run: |
        RELEASE_DATE=$(date +"%d%m%Y")
        echo "RELEASE_DATE=$RELEASE_DATE" >> $GITHUB_ENV

    - name: Publish to Docker Hub with release date tag
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker tag ubuntu:1.0 ${{ secrets.DOCKER_HUB_USERNAME }}/ubuntu:$RELEASE_DATE
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ubuntu:$RELEASE_DATE
